### ISSUE TITLE
Question: Host and token

### ISSUE THREAD

**Issue by Piioo** [piesync/billbo#73]
Hello,

when i do not add Billbo.token or host i do not get an error.

What ist the Bilbo.token? The scripe secret_key?
What is the Bilbo.host? API URL from stripe?

Is there an description of this?

Piioo

**Comment by Piioo** [comment]
ok I understand now.

Billbo is not only nice gem. It is an app which have to be running next to our app...

**Comment by challengee** [comment]
That's correct! You can find a list of all the things you can configure here: https://github.com/piesync/billbo/blob/master/config/configuration.rb
